//
//  NetworkManager.swift
//  MVP
//
//  Created by Nikita Alpatiev on 1/30/23.
//

// MARK: - Mock class

final class NetworkDataManager {
    static let someData = [Student(name: "Константин Киселев",
                                   image: "Konstantin",
                                   team: "Двоичный кот",
                                   message: "Привет",
                                   score: 12440,
                                   homeworksPassed: 13),
                           Student(name: "Ян Жигурс",
                                   image: "Yan",
                                   team: "В поисках bugs",
                                   message: "Привет",
                                   score: 14520,
                                   homeworksPassed: 14),
                           Student(name: "Никита Алпатьев",
                                   image: "Nikita",
                                   team: "Двоичный кот",
                                   message: "Привет ",
                                   score: 13430,
                                   homeworksPassed: 14),
                           Student(name: "Гарицкий Виктор",
                                   image: "Victor",
                                   team: "В поисках bugs",
                                   message: "Привет",
                                   score: 11490,
                                   homeworksPassed: 14),
                           Student(name: "Станислав Свентский",
                                   image: "Stanislav",
                                   team: "Двоичный Кот",
                                   message: "Привет",
                                   score: 9700,
                                   homeworksPassed: 11),
                           Student(name: "Сергей Галкин",
                                   image: "Galkin",
                                   team: "teamDev",
                                   message: "Привет",
                                   score: 6310,
                                   homeworksPassed: 8),
                           Student(name: "Камилла Багаева",
                                   image: "image",
                                   team: "Двоичный кот",
                                   message: "Привет",
                                   score: 2480,
                                   homeworksPassed: 6),
                           Student(name: "Олга Михаилова",
                                   image: "image",
                                   team: "Двоичный кот",
                                   message: "Привет",
                                   score: 4410,
                                   homeworksPassed: 14),
                           Student(name: "Дмитрий Зыбкин",
                                   image: "image",
                                   team: "Двоичный кот",
                                   message: "Привет",
                                   score: 5830,
                                   homeworksPassed: 8),
                           Student(name: "Хайруллин Булат",
                                   image: "image",
                                   team: "Двоичный кот",
                                   message: "Привет",
                                   score: 540,
                                   homeworksPassed: 0),
                           Student(name: "Илья Добрянский",
                                   image: "image",
                                   team: "В поисках bugs",
                                   message: "Привет",
                                   score: 920,
                                   homeworksPassed: 1),
                           Student(name: "Роман Дубина",
                                   image: "image",
                                   team: "Двоичный кот",
                                   message: "Привет",
                                   score: 13220,
                                   homeworksPassed: 14),
                           Student(name: "Дмитрий Новиков",
                                   image: "image",
                                   team: "Двоичный кот",
                                   message: "Привет",
                                   score: 0,
                                   homeworksPassed: 0),
                           Student(name: "admin",
                                   image: "person",
                                   team: "unknown",
                                   message: "Привет",
                                   score: 1,
                                   homeworksPassed: 0)
    ]
}
